### ISSUE TITLE
Bug in showSeasons Function

### ISSUE THREAD

**Issue by ByronTudhope** [Kryptonit3/SickRage#1]
SickRage handles "Specials" as season 0. You've used `null` as the default parameter for the function 'showSeasons' and you're the check below to exclude the parameter 'season' from being passed on to the SickRage API if it is `null`. This simply changes the check to look for `null` specifically allowing `0` to be passed as a parameter.

The line is function showSeasons reads:
`if ( $season ) { $uriData['season'] = $season; }`
can you please change it to
`if ( $season !== null ) { $uriData['season'] = $season; }`

https://github.com/Kryptonit3/SickRage/blob/master/src/SickRage.php#L686

Thanks for the awesome library, it is much appreciated! If you'd like me to fork and submit a pull request, let me know and I will. Didn't seem worth it for such a small change.

**Comment by Kryptonit3-zz** [comment]
This should work. Let me know if it doesn't.

https://github.com/Kryptonit3/SickRage/commit/441a293b5c219c3cdd1ebebd2bcf4518598f84aa

update and it should pull release 1.0.1
